Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-06d5c50c30a35fb88"
      Tags: 
      - Key: "Name"
        Value: "Change1"