Mappings: 
  AmiRegionMap: 
    us-east-1: 
      AMI: "ami-03c7d01cf4dedc891"
    us-east-2: 
      AMI: "ami-06d5c50c30a35fb88"
    us-west-1: 
      AMI: "ami-0583a1f1cd3c11ebc"
    us-west-2:
      AMI: "ami-0ac64ad8517166fb1"
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: "t2.micro"
      ImageId: !FindInMap
      - AmiRegionMap
      - !Ref AWS::Region
      - AMI
      Tags:
      - Key: "Name"
        Value: !Join ["-", [my, instance, from, CloudFormation]]
      SecurityGroups:
      - !Ref VprofileSG
  VprofileSG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow ssh & http from MyIP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 89.138.206.79/32