Parameters:
  NameOfService:
    Description: "The name of the service this stack is to be used for"
    Type: String
  InstanceTypeParameter:
    Type: String
    Default: "t2.micro"
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - m1.small
      - m1.large
    Description: Enter t2.micro, t2.small, t2.medium, m1.small or m1.large. Default is t2.micro.
  KeyName:
    Description: Name of EC2 login Key
    Type: AWS::EC2::KeyPair::KeyName
Mappings:
  AmiRegionMap: 
    us-east-1: 
      AMI: "ami-03c7d01cf4dedc891"
    us-east-2: 
      AMI: "ami-06d5c50c30a35fb88"
    us-west-1: 
      AMI: "ami-0583a1f1cd3c11ebc"
    us-west-2:
      AMI: "ami-0ac64ad8517166fb1"
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      KeyName: !Ref KeyName
      ImageId: !FindInMap
      - AmiRegionMap
      - !Ref AWS::Region
      - AMI
      Tags:
      - Key: "Name"
        Value: !Ref NameOfService
      SecurityGroups:
      - !Ref VprofileSG
  VprofileSG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow ssh & http from MyIP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 89.138.206.79/32
Outputs:
  PrintSomeInfo:
    Value: !GetAtt
    - MyEC2Instance
    - PublicDnsName